FROM node:22.20-bookworm-slim AS builder
WORKDIR /app

# Install pnpm
RUN npm install -g pnpm@10.6.1

# Copy everything
COPY . .

# Install dependencies and build
RUN pnpm install
RUN pnpm --filter ./apps/backend run build

# Production stage
FROM node:22.20-bookworm-slim
WORKDIR /app

# Install OpenSSL and CA Certificates required by Prisma for SSL PostgreSQL connections
RUN apt-get update -y && apt-get install -y openssl ca-certificates && rm -rf /var/lib/apt/lists/*

RUN npm install -g pnpm@10.6.1

# Copy from builder
COPY --from=builder /app /app

# Expose backend port
EXPOSE 3000

# Fix Node.js out of memory crashes on Render's 512MB free tier
ENV NODE_OPTIONS="--max-old-space-size=350"

# Start backend using Node directly
CMD ["node", "--experimental-require-module", "./apps/backend/dist/apps/backend/src/main.js"]

